version: '3.8'

services:
  wings:
    image: ghcr.io/pterodactyl/wings:develop@sha256:2f066cd556aeea400c21b8766dc66dd75eac73adf9583696410d90592bc4b0d2
    restart: always
    ports:
      - "8081:8081"
      - "2022:2022"
    tty: true
    environment:
      TZ: "Asia/Karachi"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: ubuntu
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pterodactyl/:/etc/pterodactyl/"
      - "/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"
